# Generated by Django 3.0.7 on 2023-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='cess',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='eway',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='po',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='tcs',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='veh',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='cess',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='eway',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='po',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='tcs',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='veh',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='gstin',
        ),
        migrations.AddField(
            model_name='supplier',
            name='krapin',
            field=models.CharField(default='name', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
