# Generated by Django 3.0.7 on 2023-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20230419_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='krapin',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
